// Row aliases for the reader-facing catalog views — AGENTS.md Data Contract.
//
// `books_catalog` and `chapters_catalog` are the ONLY tables/views this app
// reads for catalog data: they run `security_invoker = on`, exclude drafts
// by construction, and pre-compute the aggregates that make `books` + a
// per-row `chapters` count an N+1. Never query `books` or `chapters`
// directly, and never reference `chapters_list` or
// `chapters_needing_attention` — both are admin-only.
//
// Derived from the generated `types/database.ts` via Supabase's `Tables<>`
// helper (https://supabase.com/docs/reference/javascript/typescript-support).
// Never hand-edit `database.ts` — it is regenerated by `npm run types:gen`.
import type { Tables } from "@/types/database";

/**
 * One row per published book (drafts are excluded by the view itself).
 *
 * Nullable columns carry real UI states, not edge cases:
 * - `total_duration_seconds`: null means duration UNKNOWN (no chapter has a
 *   measured duration yet), NOT zero. Never render "00:00" for null — use
 *   `formatDuration()` from `lib/format.ts`.
 * - `cover_path`: null is a legitimate, expected state. Resolve it to the
 *   local placeholder from `constants/images.ts`, never a broken image.
 * - Every other nullable column reflects the view's `left join` shape (a
 *   book row always exists if the view returned it, but Postgres still
 *   types aggregate/view columns as nullable).
 */
export type BookCatalogRow = Tables<"books_catalog">;

/**
 * The column subset M3's hero card and carousels actually render. Every
 * `lib/queries/catalog.ts` fetcher selects exactly these columns (never
 * `select('*')` — prompt 11 step 2), so this is the honest return type
 * rather than the full `BookCatalogRow` shape those queries don't fetch.
 */
export type CarouselBookRow = Pick<
  BookCatalogRow,
  | "id"
  | "title"
  | "author"
  | "genres"
  | "cover_path"
  | "chapter_count"
  | "audio_count"
  | "free_chapter_count"
  | "total_duration_seconds"
  | "created_at"
  | "updated_at"
>;

/** The column subset M8's result rows render — `lib/queries/search.ts` selects exactly these. */
export type SearchBookRow = Pick<
  BookCatalogRow,
  | "id"
  | "title"
  | "author"
  | "cover_path"
  | "chapter_count"
  | "audio_count"
  | "total_duration_seconds"
>;

/** The column subset M4's header renders — `bookDetailOptions()` selects exactly these. */
export type BookDetailRow = Pick<
  BookCatalogRow,
  | "id"
  | "title"
  | "author"
  | "synopsis"
  | "short_description"
  | "genres"
  | "maturity"
  | "cover_path"
  | "chapter_count"
  | "audio_count"
  | "total_duration_seconds"
>;

/**
 * Chapter metadata only — no `script_text` (the view omits it; fetch prose
 * per chapter from `chapters.script_text` via its own query, never here).
 *
 * - `audio_duration_seconds`: null means duration UNKNOWN, same rule as
 *   above. A file can exist in storage with no measured duration.
 * - `has_audio` / `has_text`: booleans computed by the view; prefer these
 *   over inferring presence from a nullable path column.
 */
export type ChapterCatalogRow = Tables<"chapters_catalog">;

/** The column subset M4's chapter preview rows render — `chapterPreviewOptions()` selects exactly these. */
export type ChapterPreviewRow = Pick<
  ChapterCatalogRow,
  "id" | "number" | "title" | "access" | "has_audio" | "audio_duration_seconds"
>;

/**
 * Enough of a chapter to run the lock check and navigate — M4's Listen
 * target and M5's previous and next chapters.
 */
export type ChapterTargetRow = Pick<ChapterCatalogRow, "id" | "number" | "access">;

/** The column subset M5 reads for the open chapter — `chapterDetailOptions()` selects exactly these. */
export type ChapterDetailRow = Pick<
  ChapterCatalogRow,
  "id" | "book_id" | "number" | "title" | "access" | "has_text" | "has_audio"
>;
